server:
  port: ${PORT:8989}

management:
  port: 8990

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true

turbine:
  clusterNameExpression: new String("default")
  appConfig: menu-service
  instanceInsertPort: false
  instanceUrlSuffix:
    default: :9180/hystrix.stream  # 'default' equals CLUSTER NAME

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
management:
  port: -1
turbine:
  instanceUrlSuffix: /hystrix.stream
