{{ if .Values.global.useConfigServerBootstrap }}
{{ else if .Values.config.existingConfigMapName }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: turbine-server
data:
  bootstrap.yaml: |+
    server:
      port: {{ .Values.service.stream.internalPort }}
    spring:
      application:
        name: turbine-server
      cloud:
        config:
{{ if .Values.spring.cloud.config.enabled }}
          enabled: {{ .Values.spring.cloud.config.enabled }}
          uri: {{ required "A valid value of spring.cloud.config.uri is required!" .Values.spring.cloud.config.uri }}
{{ else }}
          enabled: false
{{ end }}
  application.yaml: |+
    management:
      port: {{ .Values.service.mgmt.internalPort }}

    eureka:
      client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
          defaultZone: {{ .Values.eureka.client.serviceUrl.defaultZone }}

    spring:
      rabbitmq:
        addresses: {{ .Values.rabbitmq.url }}
        host: {{ .Values.rabbitmq.host }}
        port: {{ .Values.rabbitmq.port }}
        username: {{ .Values.rabbitmq.username }}
        password: {{ .Values.rabbitmq.password }}
        virtual-host: {{ .Values.rabbitmq.virtualHost }}
{{ if .Values.rabbitmq.sslEnabled }}
        ssl:
          enabled: {{ .Values.rabbitmq.sslEnabled }}
{{ end }}

{{ end }}
