apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{  .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: turbine-server
spec:
  replicas:  {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        component: turbine-server
    spec:
      containers:
      - name: turbine-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: stream
          containerPort: {{ .Values.service.stream.internalPort }}
        - name: mgmt
          containerPort: {{ .Values.service.mgmt.internalPort }}
        volumeMounts:
        - mountPath: /config
          name: turbine-server-config
      volumes:
      - name: turbine-server-config
{{ include "configServerBootstrap" . }}

