# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: ibmcase/turbine-server
  tag: latest
  pullPolicy: Always

service:
  name:
  type: ClusterIP
  stream:
    port: 8989
    internalPort: 8989
  mgmt:
    port: 8990
    internalPort: 8990

config:
  existingConfigMapName:

spring:
  cloud:
    config:
      enabled: false
      uri:

eureka:
  client:
    serviceUrl:
      defaultZone:
      
rabbitmq:
  url:
  host:
  port:
  username:
  password:
  virtualHost:
  sslEnabled: 

global:
  useConfigServerBootstrap: false
