# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: jkwong/turbine-server
  tag: latest
  pullPolicy: Always

service:
  name: turbine-server
  type: ClusterIP
  port: 8989
  internalPort: 8989

config:
  existingConfigMapName:

spring:
  cloud:
    config:
      enabled: false
      uri:

rabbitmq:
  url:
  host:
  port:
  username:
  password:
  virtualHost:
  sslEnabled: 

